- name: Allow http/https
  command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https

- name: Bounce firewalld
  service: name=firewalld state=restarted
  when: "'con01' not in inventory_hostname_short"
